### ISSUE TITLE
Action to take due to impending CRAN archival of R package isoband

### ISSUE THREAD

**Issue by jakobdambon** [jakobdambon/varycoef#12]
We are monitoring the development of a potential archival of the package `isoband` on CRAN. 

The dependencies between the `varycoef`  and `isoband`  are as follows:

```
pak::pkg_deps_explain("varycoef", "isoband")
varycoef -> mlr -> ggplot2 -> isoband                                       
varycoef -> mlrMBO -> mlr -> ggplot2 -> isoband
varycoef -> mlrMBO -> smoof -> ggplot2 -> isoband
varycoef -> mlrMBO -> smoof -> plotly -> ggplot2 -> isoband
varycoef -> smoof -> ggplot2 -> isoband
varycoef -> smoof -> plotly -> ggplot2 -> isoband
```

Therefore, *only* the model-based optimization in the selection procedure (PMLE) is affected. 

As of right now, the CRAN checks still give an error, [link](https://cran.r-project.org/web/checks/check_results_isoband.html). The maintainers are working on it, both of `isoband`  and `ggplot2`, see below:

        This should now be fixed on github. Again, if somebody could confirm that things now work for LLVM clang 15.0.0 that would be great.

_Originally posted by @clauswilke in https://github.com/wilkelab/isoband/issues/33#issuecomment-1268398520_

**Comment by clauswilke** [comment]
Updated isoband is on CRAN now.
