### ISSUE TITLE
Good Formula Implementation

### ISSUE THREAD

**Issue by jakobdambon** [jakobdambon/varycoef#3]
Be able to use formula notation like `y ~ (x1 | s1 + ... + sd) + (x2 || s1 + ... + sd) + x3` to define a GP-based SVC model, where: 

- `(x1 | s1 + ... + sd)` is a fixed **and** random effect (SVC) with coordinates `s1` to `sd`.
- `(x1 || s1 + ... + sd)` like above, but `||` indicates an SVC without fixed effect / mean. 
- `x3` is only a fixed effect without random effect (SVC)

An SVC for the intercept is only added when a `1` is provided.

**Comment by reinhardfurrer** [comment]
Gilles has implemented the formula notation in `abn`. I believe it was too complicated as he has done it from scratch (dissecting the formula argument). Possibly use the standard/"stats" approach as in `lm` to get the `model.matrix` stuff and a second iteration for the random part. I am not much of a regexp'er, hence glancing at `abn` would be inspiring for me.

**Comment by jakobdambon** [comment]
Calls with formulas are supported in the following way:

- use the argument 'data' and 'formula' ('SVC_mle.formula' method)
